language: android
jdk: oraclejdk7

android:
  components:
      - build-tools-20.0.0
      - android-19
      - addon-google_apis-google-19
      - sys-img-armeabi-v7a-android-19
      - extra-android-support
      - extra-google-google_play_services
      - addon-google_apis-google-4
