language: android
jdk: oraclejdk7

android:
  components:
      - build-tools-20.0.0
      - android-19
      - android-support-v4
      - extra-android-support
      - extra-google-google_play_services
      - addon-google_apis-google-4
  licenses:
      - android-sdk-license-5be876d5
      - android-sdk-license-598b93a6
