language: android
jdk: oraclejdk7

android:
  components:
      - build-tools-20.0.0
      - android-19
      - android-support-v4
      - extra-android-support
      - platform-tools
  licenses:
      - android-sdk-license-5be876d5
      - android-sdk-license-598b93a6
